import React from 'react';

import Section from '../../Section';
import styles from '../../../styles/LandingEcosystem.module.scss';
import Image from 'next/image';
import Button from '../../Button';
import { AnimatedText } from '../../Text/Text';
const LandingEcosystem = () => {
  return (
    <Section className={styles.landingEcosystem}>
      <AnimatedText>
        <h2>A larger ecosystem that empowers all</h2>
      </AnimatedText>

      <div className={styles.descs}>
        <div className={styles.para}>
          At hop3, we nurture a unique ecosystem that empowers a community of
          consumers, web3 enthusiasts, digital creators and brands through
          aligned incentives and distribution of influence. We believe in
          transparency and the voice of the consumer, expressed via
          user-generated content (UGC).
        </div>
        <div className={styles.para}>
          Rather than relying on traditional advertisers and third-party
          platforms to tell us where to shop, eat and go, hop3 community members
          share cool spots, deals and tips with their peers, in return for
          rewards and social recognition.
        </div>
      </div>

      <div className={styles.for}>
        <h3 className={styles.text}>
          for the digital natives👾, <br /> the adventurers⛷️,
          <br /> the fun-lovers💃, and <br /> the hoppers🥳
        </h3>

        <div className={styles.image}>
          <Image
            src="/vectors/ecosystem.svg"
            alt="ecosystem"
            width={100}
            height={100}
          />
        </div>
      </div>

      <div className={styles.allocation}>
        <div className={styles.text}>
          <h3>Fair Allocation of Rewards</h3>

          <p>
            On conventional social media platforms, viewership & engagement is a
            crucial part of the platform’s monetization equation, yet users do
            not receive their share of the income generated.
          </p>
          <p>
            At hop3, we redistribute any monetization income generated by
            user-generated content proportionally back to all digital creators
            and content viewers in the form of rewards tokens.
          </p>
        </div>
        <div className={styles.imgContainer}>
          <div className={styles.coins}>
            <Image
              src="/vectors/coin-1.svg"
              alt="coins"
              width={97}
              height={139}
            />
            <Image
              src="/vectors/coin-2.svg"
              alt="coins"
              width={64}
              height={87}
            />
          </div>
        </div>
        <div className={styles.imgContainer}>
          <div className={styles.brands}>
            <Image
              src="/vectors/brands.svg"
              alt="brands"
              width={140}
              height={213}
            />
          </div>
        </div>
        <div className={styles.text}>
          <h3>hop3 for brands</h3>

          <p>
            hop3 provides an open, creative space for brands & event organizers
            to interact with consumers & participants in unprecedented ways.
          </p>
          <p>
            Build trustful relationships with the community and members will
            reciprocate with content endorsing your brand.
          </p>

          <Button variant="dark-outlined" lg>
            Contact us
          </Button>
        </div>
      </div>
    </Section>
  );
};

export default LandingEcosystem;
